### ISSUE TITLE
authorized-keys not being populated?

### ISSUE THREAD

**Issue by jongillies** [jen20/packer-ubuntu-zfs#1]
Greeting, James!  Thanks for the great article and hard work putting this together!

I was able to run the packer build for yakety just fine.  However, when I specified an existing ssh key and tried to login with that with ubuntu@, no joy.  (password prompt)

I even created a new key and tried that, no joy. (password prompt)

I wonder if you have any ideas whats going on here?

Let me know!

Oh, BTW.. I tested the xenial and that works just fine with ssh ubuntu@.

Thanks,
Jon.

**Comment by jen20** [comment]
Hi @jongillies! Sorry for the delay in responding here... I believe the version of `cloud-init` needs to be different for Yakkety. I'm planning to update this for 18.04 when it becomes available next week.

**Comment by jen20** [comment]
Hi @jongillies! I've added an Ubuntu 18.04 builder in #2 which works correctly from my testing - hopefully that will solve your issue here? I'm planning to only add LTS releases to this repo from hereon in.

**Comment by jen20** [comment]
Now that Bionic is merged, I'll go ahead and close this for now. Sorry for the initial delay in replying!
