### ISSUE TITLE
focal - package compatibility with ubuntu cloud-images

### ISSUE THREAD

**Issue by fred-vogt** [jen20/packer-ubuntu-zfs#21]
Huge fan of this repo.

It might be desirable to have "full" package parity with the default ext4 cloud-images.

The `Install standard packages` portion of [chroot-bootstrap.sh](https://github.com/jen20/packer-ubuntu-zfs/blob/c3d0f51b09ae0cc3349b369660e99b13a7329c51/focal/scripts/chroot-bootstrap.sh#L60) is missing these packages from the standard ubuntu cloud-images AMIs:
```
ubuntu-server
acpid
ec2-hibinit-agent
ec2-instance-connect
hibagent
krb5-locales
ncurses-term
ssh-import-id
xauth
```
* https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.manifest

I can create a PR to add these.

**Comment by jen20** [comment]
Hi @fred-vogt! Sorry for the delay in responding here. I'll merge a PR that adds this if you'd like to open one?

**Comment by fred-vogt** [comment]
@jen20 - Excellent James, will create a PR for this.

**Comment by jen20** [comment]
Thanks for the PR!
