### ISSUE TITLE
ena_support fails

### ISSUE THREAD

**Issue by stevenmcastano** [jen20/packer-ubuntu-zfs#7]
If I try to do a build with the ena_support line still in there it fails and tells me it's not a valid parameter. However, if I remove that line from the .json file it seems to build fine. Is there a new name for it, or any way to add the enhanced network support back in?

**Comment by jen20** [comment]
This seems like it's some kind of Packer regression - I'll investigate shortly. Sorry for the delay in replying here.

**Comment by jen20** [comment]
I believe this was related to hashicorp/packer#7143 but possibly also other things. Either way, with Packer v1.5.5 and the 20.04 template it seems resolved. Thanks for reporting, @stevenmcastano!
