### ISSUE TITLE
Any planned support for ZFS 0.8.1 now that it's out?

### ISSUE THREAD

**Issue by stevenmcastano** [jen20/packer-ubuntu-zfs#8]
The build script works great for building 18.04 after disabling ena_support but it's still using the default ubuntu packages for zfs 0.7.5 which are seriously outdates. The 0.7.5 branch is up to 0.7.13 and a few newer releases are out with significant performance upgrades on release 0.8.1 which is availible in by source as well as a few reliable PPAs.

Is there any way to update these templates and scripts to build rpool on 0.8.1?

**Comment by jen20** [comment]
Do you know of a trusted PPA to use for this? There's no reason in principle not to use v0.8.1 (and, as you say, lots of benefits!).

**Comment by jen20** [comment]
Hi @stevenmcastano! Thanks for reporting this - I've added a builder for Ubuntu 20.04 which pulls in a reasonably late release of ZOL.
